version: '3'

name: market

services:
  server:
    image: server
    build:
      context: ./market_server
    container_name: server
    ports:
      - 8000:8000
    volumes:
      - ./market_server/db.sqlite3:/project/db.sqlite3

  web-client:
    image: web-client
    build:
      context: ./market_web_client
    container_name: web-client
    ports:
      - 3000:3000
    environment:
      - API_BASE_URL=http://server:8000/api
    command: npm run start-docker
    depends_on:
      - server
