# Generated by Django 4.2.1 on 2023-05-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='adress_city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='adress_neighborhood',
            new_name='address_neighborhood',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='adress_state',
            new_name='address_state',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='adress_street',
            new_name='address_street',
        ),
    ]
