# Generated by Django 4.2.1 on 2023-06-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_customuser_address_cep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
